services:
  otel-collector:
    container_name: otel-collector
    image: "otel/opentelemetry-collector:latest"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "./otel-collector-config.yaml:/etc/otel-collector-config.yaml"
    depends_on:
      - jaeger-all-in-one
    networks:
      - default

  lightstep:
    image: lightstep/developer-satellite:latest
    container_name: lightstep
    restart: always
    networks:
      - default
    environment:
      - 'COLLECTOR_PROJECT_NAME={PROJECT}'
      - 'COLLECTOR_API_KEY={KEY}'
      - 'COLLECTOR_ROUTING_TAGS=developer_name:{EMAIL},project_name:{PROJECT},developer_mode:true'
      - 'COLLECTOR_HTTP_PLAIN_PORT=8360'
      - 'COLLECTOR_ADMIN_PLAIN_PORT=8361'
      - 'COLLECTOR_DISABLE_ACCESS_TOKEN_CHECKING=true'

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    networks:
      - default

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
    networks:
      - default
    depends_on:
      otel-collector:
        condition: service_started

networks:
  default: