services:
  otel-collector-demo:
    container_name: otel-collector-demo
    image: "otel/opentelemetry-collector:latest"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "./otel-collector-config.yaml:/etc/otel-collector-config.yaml"
    networks:
      - default

  jaeger-demo:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger-demo
    command: [ "--query.max-clock-skew-adjustment", "500ms" ]
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger_data:/badger
    ports:
      - "16686:16686" # UI
      - "4317" # OTLP gRPC default port
    depends_on:
      - otel-collector-demo
    networks:
      - default

  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
    networks:
      - default
    depends_on:
      otel-collector-demo:
        condition: service_started

networks:
  default:

volumes:
  jaeger_data:
